### ISSUE TITLE
Virus choose?

### ISSUE THREAD

**Issue by WhiteHatEthicalHacker** [Gameye98/vbug#6]
Either I'm a absolute idiot or I'm a absolute idiot
Can someone provide some context on this 
![Screenshot_2023-02-03-15-56-30-46_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/124400694/216709240-b2703fb6-c6ed-4585-b177-67c5ca200cb2.jpg)

**Comment by Gameye98** [comment]
after downloading the virus, u need to input 0 to back to main menu

**Comment by WhiteHatEthicalHacker** [comment]
> after downloading the virus, u need to input 0 to back to main menu

Alr the,
